jobs:
  build-and-test:
    macos:
      xcode: 12.5.1
    steps:
      ...
      - run:
          name: Run tests
          command: "xcodebuild \
  -project NDCalc.xcodeproj \
  -scheme NDCalc \
  -sdk iphonesimulator \
  -destination 'platform=iOS Simulator,name=iPhone 12,OS=15.5' \
  test"
